[package]
name = "sherpa"
version = "0.1.0"
edition = "2021"

[dependencies]
# Errors
anyhow = "1.0.86"

# CLI
clap = { version = "4.5.16", features = ["derive"] }

# Serialization
serde = "1.0.208"
serde_derive = "1.0.208"
toml = "0.8.19"

# Libvirt
virt = { version = "0.4.1", features = ["qemu"] }

# Templates
askama = "0.12.1"

# Random number generator
rand = "0.8.5"

# Docker Integration
# bollard = "0.17.1"

# Async
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.30"

# file system
shellexpand = "3.1.0"


[dev-dependencies]
regex = "1.10.6"
