# Speed up SSH key generation in debug mode.
[profile.dev.package.num-bigint-dig]
opt-level = 3
# Use once it becomes available in the ssh-key crate release.
# [profile.dev.package.crypto-bigint]
# opt-level = 3

[workspace]
resolver = "3"
members = [
  "crates/client",
  "crates/container",
  "crates/ctl",
  "crates/db",
  "crates/network",
  "crates/libvirt",
  "crates/server",
  "crates/shared",
  "crates/template",
  "crates/topology",
  "crates/validate",
]
default-members = ["crates/client"]
