[package]
name = "sherpa"
version = "0.1.0"
edition = "2021"

# Speed up SSH key generation in debug mode.
[profile.dev.package.num-bigint-dig]
opt-level = 3

[dependencies]
# Errors
anyhow = "1.0.100"

# CLI
clap = { version = "4.5.16", features = ["derive"] }

# Serialization/Deserialization
serde = "1.0.208"
serde_derive = "1.0.208"
serde_json = "1.0.128"
serde_yaml = "0.9.34"
toml = "0.8.19"
toml_edit = "0.22.22"

# Libvirt
virt = { version = "0.4.1", features = ["qemu"] }

# Containers
# oci-client = "0.15"
bollard = "0.19.3"

# De/Compression
async-compression = { version = "0.4.32", features = ["tokio", "gzip"] }

# Templates
askama = "0.14.0"

# Random number generator
rand = "0.8.5"

# Random names
petname = "2.0.2"

# Async
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.31"
futures-util = "0.3.31"

# File system
shellexpand = "3.1.0"

# Encoding/decoding
base64 = "0.22.1"
md5 = "0.7.0"
sha2 = "0.10.8"
twox-hash = "2.0.0"

# Generate SSH keys
ssh-key = { version = "0.6.6", features = ["rsa", "ed25519"] }

# IP Addressing
ipnetwork = { version = "0.21.1", features = ["serde"] }

[dev-dependencies]
regex = "1.10.6"
tempfile = "3.14.0"
serde_test = "1.0.177"
