# Speed up SSH key generation in debug mode.
[profile.dev.package.num-bigint-dig]
opt-level = 2

[workspace]
resolver = "3"
members = ["client", "core", "container", "data", "libvirt", "main", "server", "template", "topology", "util"]
