[package]
name = "sherpa"
version = "0.1.0"
edition = "2021"

# Speed up SSH key generation in debug mode.
[profile.dev.package.num-bigint-dig]
opt-level = 3

[dependencies]
# Errors
anyhow = "1.0.86"

# CLI
clap = { version = "4.5.16", features = ["derive"] }

# Serialization
serde = "1.0.208"
serde_derive = "1.0.208"
serde_json = "1.0.128"
serde_yaml = "0.9.34"
toml = "0.8.19"
toml_edit = "0.19"

# Libvirt
virt = { version = "0.4.1", features = ["qemu"] }

# Templates
askama = "0.12.1"

# Random number generator
rand = "0.8.5"

# Random names
petname = "2.0.2"

# Docker Integration
# bollard = "0.17.1"

# Async
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.30"

# file system
shellexpand = "3.1.0"

# encoder/decoders
base64 = "0.22.1"
md5 = "0.7.0"
sha2 = "0.10.8"
twox-hash = "2.0.0"

# Generate SSH keys
ssh-key = { version = "0.6.6", features = ["rsa", "ed25519"] }

# IP Addressing
ipnetwork = "0.20.0"

[dev-dependencies]
regex = "1.10.6"
tempfile = "3.14.0"
serde_test = "1.0.177"
