[package]
name = "sherpa"
version = "0.1.0"
edition = "2021"

[dependencies]
# Errors
anyhow = "1.0.86"

# CLI
clap = { version = "4.5.16", features = ["derive"] }

# Serialization
serde = "1.0.208"
serde_derive = "1.0.208"
toml = "0.8.19"

# Libvirt
virt = { version = "0.4.0", features = ["qemu"] }

# Templates
askama = "0.12.1"
