[package]
name = "validate"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
topology = { path = "../topology" }

# Errors
anyhow = "1.0.100"

# Logging
tracing = "0.1"
