[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
data = { path = "../data" }
util = { path = "../util" }

# Errors
anyhow = "1.0.100"

# Serialization
serde_derive = "1.0.208"

# IP Addressing
ipnetwork = { version = "0.21.1", features = ["serde"] }
