[package]
name = "libvirt"
version = "0.3.1"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

# Errors
anyhow = "1.0.100"

# Logging
tracing = "0.1"

# Libvirt
virt = { version = "0.4.1", features = ["qemu"] }
