[package]
name = "sherpa-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
